// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDdC5RjMh1yniandZyY5FYltczZrO_2evo',
    appId: '1:993617293473:web:5091fb52d76ba9404700e0',
    messagingSenderId: '993617293473',
    projectId: 'snapshop-2875a',
    authDomain: 'snapshop-2875a.firebaseapp.com',
    storageBucket: 'snapshop-2875a.appspot.com',
    measurementId: 'G-W5LEJWW77M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDANj6Pq7kF_pUOKXJAudHR-GzggNNoFJQ',
    appId: '1:993617293473:android:e7912e52f36ef6204700e0',
    messagingSenderId: '993617293473',
    projectId: 'snapshop-2875a',
    storageBucket: 'snapshop-2875a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA403NHSdivfZS98n57_3Wiim8IZLbXMFg',
    appId: '1:993617293473:ios:aef0424c1ca471134700e0',
    messagingSenderId: '993617293473',
    projectId: 'snapshop-2875a',
    storageBucket: 'snapshop-2875a.appspot.com',
    iosBundleId: 'com.example.ecommerceC8Online',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA403NHSdivfZS98n57_3Wiim8IZLbXMFg',
    appId: '1:993617293473:ios:aef0424c1ca471134700e0',
    messagingSenderId: '993617293473',
    projectId: 'snapshop-2875a',
    storageBucket: 'snapshop-2875a.appspot.com',
    iosBundleId: 'com.example.ecommerceC8Online',
  );
}
